
name: Keep Server Alive
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to keep backend active
        run: curl -X GET https://aiquerynet-backend.onrender.com/health
